module EInvoiceAPI
  class Client < EInvoiceAPI::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader documents: EInvoiceAPI::Resources::Documents

    attr_reader inbox: EInvoiceAPI::Resources::Inbox

    attr_reader outbox: EInvoiceAPI::Resources::Outbox

    attr_reader validate: EInvoiceAPI::Resources::Validate

    attr_reader lookup: EInvoiceAPI::Resources::Lookup

    attr_reader me: EInvoiceAPI::Resources::Me

    attr_reader webhooks: EInvoiceAPI::Resources::Webhooks

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
