module EInvoiceAPI
  module Models
    type charge =
      {
        amount: String?,
        base_amount: String?,
        multiplier_factor: String?,
        reason: String?,
        reason_code: EInvoiceAPI::Models::Charge::reason_code?,
        tax_code: EInvoiceAPI::Models::Charge::tax_code?,
        tax_rate: String?
      }

    class Charge < EInvoiceAPI::Internal::Type::BaseModel
      attr_accessor amount: String?

      attr_accessor base_amount: String?

      attr_accessor multiplier_factor: String?

      attr_accessor reason: String?

      attr_accessor reason_code: EInvoiceAPI::Models::Charge::reason_code?

      attr_accessor tax_code: EInvoiceAPI::Models::Charge::tax_code?

      attr_accessor tax_rate: String?

      def initialize: (
        ?amount: String?,
        ?base_amount: String?,
        ?multiplier_factor: String?,
        ?reason: String?,
        ?reason_code: EInvoiceAPI::Models::Charge::reason_code?,
        ?tax_code: EInvoiceAPI::Models::Charge::tax_code?,
        ?tax_rate: String?
      ) -> void

      def to_hash: -> {
        amount: String?,
        base_amount: String?,
        multiplier_factor: String?,
        reason: String?,
        reason_code: EInvoiceAPI::Models::Charge::reason_code?,
        tax_code: EInvoiceAPI::Models::Charge::tax_code?,
        tax_rate: String?
      }

      type reason_code =
        :AA
        | :AAA
        | :AAC
        | :AAD
        | :AAE
        | :AAF
        | :AAH
        | :AAI
        | :AAS
        | :AAT
        | :AAV
        | :AAY
        | :AAZ
        | :ABA
        | :ABB
        | :ABC
        | :ABD
        | :ABF
        | :ABK
        | :ABL
        | :ABN
        | :ABR
        | :ABS
        | :ABT
        | :ABU
        | :ACF
        | :ACG
        | :ACH
        | :ACI
        | :ACJ
        | :ACK
        | :ACL
        | :ACM
        | :ACS
        | :ADC
        | :ADE
        | :ADJ
        | :ADK
        | :ADL
        | :ADM
        | :ADN
        | :ADO
        | :ADP
        | :ADQ
        | :ADR
        | :ADT
        | :ADW
        | :ADY
        | :ADZ
        | :AEA
        | :AEB
        | :AEC
        | :AED
        | :AEF
        | :AEH
        | :AEI
        | :AEJ
        | :AEK
        | :AEL
        | :AEM
        | :AEN
        | :AEO
        | :AEP
        | :AES
        | :AET
        | :AEU
        | :AEV
        | :AEW
        | :AEX
        | :AEY
        | :AEZ
        | :AJ
        | :AU
        | :CA
        | :CAB
        | :CAD
        | :CAE
        | :CAF
        | :CAI
        | :CAJ
        | :CAK
        | :CAL
        | :CAM
        | :CAN
        | :CAO
        | :CAP
        | :CAQ
        | :CAR
        | :CAS
        | :CAT
        | :CAU
        | :CAV
        | :CAW
        | :CAX
        | :CAY
        | :CAZ
        | :CD
        | :CG
        | :CS
        | :CT
        | :DAB
        | :DAC
        | :DAD
        | :DAF
        | :DAG
        | :DAH
        | :DAI
        | :DAJ
        | :DAK
        | :DAL
        | :DAM
        | :DAN
        | :DAO
        | :DAP
        | :DAQ
        | :DL
        | :EG
        | :EP
        | :ER
        | :FAA
        | :FAB
        | :FAC
        | :FC
        | :FH
        | :FI
        | :GAA
        | :HAA
        | :HD
        | :HH
        | :IAA
        | :IAB
        | :ID
        | :IF
        | :IR
        | :IS
        | :KO
        | :L1
        | :LA
        | :LAA
        | :LAB
        | :LF
        | :MAE
        | :MI
        | :ML
        | :NAA
        | :OA
        | :PA
        | :PAA
        | :PC
        | :PL
        | :PRV
        | :RAB
        | :RAC
        | :RAD
        | :RAF
        | :RE
        | :RF
        | :RH
        | :RV
        | :SA
        | :SAA
        | :SAD
        | :SAE
        | :SAI
        | :SG
        | :SH
        | :SM
        | :SU
        | :TAB
        | :TAC
        | :TT
        | :TV
        | :V1
        | :V2
        | :WH
        | :XAA
        | :YY
        | :ZZZ

      module ReasonCode
        extend EInvoiceAPI::Internal::Type::Enum

        AA: :AA
        AAA: :AAA
        AAC: :AAC
        AAD: :AAD
        AAE: :AAE
        AAF: :AAF
        AAH: :AAH
        AAI: :AAI
        AAS: :AAS
        AAT: :AAT
        AAV: :AAV
        AAY: :AAY
        AAZ: :AAZ
        ABA: :ABA
        ABB: :ABB
        ABC: :ABC
        ABD: :ABD
        ABF: :ABF
        ABK: :ABK
        ABL: :ABL
        ABN: :ABN
        ABR: :ABR
        ABS: :ABS
        ABT: :ABT
        ABU: :ABU
        ACF: :ACF
        ACG: :ACG
        ACH: :ACH
        ACI: :ACI
        ACJ: :ACJ
        ACK: :ACK
        ACL: :ACL
        ACM: :ACM
        ACS: :ACS
        ADC: :ADC
        ADE: :ADE
        ADJ: :ADJ
        ADK: :ADK
        ADL: :ADL
        ADM: :ADM
        ADN: :ADN
        ADO: :ADO
        ADP: :ADP
        ADQ: :ADQ
        ADR: :ADR
        ADT: :ADT
        ADW: :ADW
        ADY: :ADY
        ADZ: :ADZ
        AEA: :AEA
        AEB: :AEB
        AEC: :AEC
        AED: :AED
        AEF: :AEF
        AEH: :AEH
        AEI: :AEI
        AEJ: :AEJ
        AEK: :AEK
        AEL: :AEL
        AEM: :AEM
        AEN: :AEN
        AEO: :AEO
        AEP: :AEP
        AES: :AES
        AET: :AET
        AEU: :AEU
        AEV: :AEV
        AEW: :AEW
        AEX: :AEX
        AEY: :AEY
        AEZ: :AEZ
        AJ: :AJ
        AU: :AU
        CA: :CA
        CAB: :CAB
        CAD: :CAD
        CAE: :CAE
        CAF: :CAF
        CAI: :CAI
        CAJ: :CAJ
        CAK: :CAK
        CAL: :CAL
        CAM: :CAM
        CAN: :CAN
        CAO: :CAO
        CAP: :CAP
        CAQ: :CAQ
        CAR: :CAR
        CAS: :CAS
        CAT: :CAT
        CAU: :CAU
        CAV: :CAV
        CAW: :CAW
        CAX: :CAX
        CAY: :CAY
        CAZ: :CAZ
        CD: :CD
        CG: :CG
        CS: :CS
        CT: :CT
        DAB: :DAB
        DAC: :DAC
        DAD: :DAD
        DAF: :DAF
        DAG: :DAG
        DAH: :DAH
        DAI: :DAI
        DAJ: :DAJ
        DAK: :DAK
        DAL: :DAL
        DAM: :DAM
        DAN: :DAN
        DAO: :DAO
        DAP: :DAP
        DAQ: :DAQ
        DL: :DL
        EG: :EG
        EP: :EP
        ER: :ER
        FAA: :FAA
        FAB: :FAB
        FAC: :FAC
        FC: :FC
        FH: :FH
        FI: :FI
        GAA: :GAA
        HAA: :HAA
        HD: :HD
        HH: :HH
        IAA: :IAA
        IAB: :IAB
        ID: :ID
        IF: :IF
        IR: :IR
        IS: :IS
        KO: :KO
        L1: :L1
        LA: :LA
        LAA: :LAA
        LAB: :LAB
        LF: :LF
        MAE: :MAE
        MI: :MI
        ML: :ML
        NAA: :NAA
        OA: :OA
        PA: :PA
        PAA: :PAA
        PC: :PC
        PL: :PL
        PRV: :PRV
        RAB: :RAB
        RAC: :RAC
        RAD: :RAD
        RAF: :RAF
        RE: :RE
        RF: :RF
        RH: :RH
        RV: :RV
        SA: :SA
        SAA: :SAA
        SAD: :SAD
        SAE: :SAE
        SAI: :SAI
        SG: :SG
        SH: :SH
        SM: :SM
        SU: :SU
        TAB: :TAB
        TAC: :TAC
        TT: :TT
        TV: :TV
        V1: :V1
        V2: :V2
        WH: :WH
        XAA: :XAA
        YY: :YY
        ZZZ: :ZZZ

        def self?.values: -> ::Array[EInvoiceAPI::Models::Charge::reason_code]
      end

      type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

      module TaxCode
        extend EInvoiceAPI::Internal::Type::Enum

        AE: :AE
        E: :E
        S: :S
        Z: :Z
        G: :G
        O: :O
        K: :K
        L: :L
        M: :M
        B: :B

        def self?.values: -> ::Array[EInvoiceAPI::Models::Charge::tax_code]
      end
    end
  end
end
