module EInvoiceAPI
  module Models
    type document_direction = :INBOUND | :OUTBOUND

    module DocumentDirection
      extend EInvoiceAPI::Internal::Type::Enum

      INBOUND: :INBOUND
      OUTBOUND: :OUTBOUND

      def self?.values: -> ::Array[EInvoiceAPI::Models::document_direction]
    end
  end
end
