module EInvoiceAPI
  module Models
    type document_type =
      :INVOICE
      | :CREDIT_NOTE
      | :DEBIT_NOTE
      | :SELFBILLING_INVOICE
      | :SELFBILLING_CREDIT_NOTE

    module DocumentType
      extend EInvoiceAPI::Internal::Type::Enum

      INVOICE: :INVOICE
      CREDIT_NOTE: :CREDIT_NOTE
      DEBIT_NOTE: :DEBIT_NOTE
      SELFBILLING_INVOICE: :SELFBILLING_INVOICE
      SELFBILLING_CREDIT_NOTE: :SELFBILLING_CREDIT_NOTE

      def self?.values: -> ::Array[EInvoiceAPI::Models::document_type]
    end
  end
end
