module EInvoiceAPI
  module Models
    type document_create =
      {
        allowances: ::Array[EInvoiceAPI::DocumentCreate::Allowance]?,
        amount_due: EInvoiceAPI::Models::DocumentCreate::amount_due?,
        attachments: ::Array[EInvoiceAPI::DocumentAttachmentCreate]?,
        billing_address: String?,
        billing_address_recipient: String?,
        charges: ::Array[EInvoiceAPI::DocumentCreate::Charge]?,
        currency: EInvoiceAPI::Models::currency_code,
        customer_address: String?,
        customer_address_recipient: String?,
        customer_email: String?,
        customer_id: String?,
        customer_name: String?,
        customer_tax_id: String?,
        direction: EInvoiceAPI::Models::document_direction,
        document_type: EInvoiceAPI::Models::document_type,
        due_date: Date?,
        invoice_date: Date?,
        invoice_id: String?,
        invoice_total: EInvoiceAPI::Models::DocumentCreate::invoice_total?,
        items: ::Array[EInvoiceAPI::DocumentCreate::Item],
        note: String?,
        payment_details: ::Array[EInvoiceAPI::PaymentDetailCreate]?,
        payment_term: String?,
        previous_unpaid_balance: EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance?,
        purchase_order: String?,
        remittance_address: String?,
        remittance_address_recipient: String?,
        service_address: String?,
        service_address_recipient: String?,
        service_end_date: Date?,
        service_start_date: Date?,
        shipping_address: String?,
        shipping_address_recipient: String?,
        state: EInvoiceAPI::Models::document_state,
        subtotal: EInvoiceAPI::Models::DocumentCreate::subtotal?,
        tax_code: EInvoiceAPI::Models::DocumentCreate::tax_code,
        tax_details: ::Array[EInvoiceAPI::DocumentCreate::TaxDetail]?,
        total_discount: EInvoiceAPI::Models::DocumentCreate::total_discount?,
        total_tax: EInvoiceAPI::Models::DocumentCreate::total_tax?,
        vatex: EInvoiceAPI::Models::DocumentCreate::vatex?,
        vatex_note: String?,
        vendor_address: String?,
        vendor_address_recipient: String?,
        vendor_email: String?,
        vendor_name: String?,
        vendor_tax_id: String?
      }

    class DocumentCreate < EInvoiceAPI::Internal::Type::BaseModel
      attr_accessor allowances: ::Array[EInvoiceAPI::DocumentCreate::Allowance]?

      attr_accessor amount_due: EInvoiceAPI::Models::DocumentCreate::amount_due?

      attr_accessor attachments: ::Array[EInvoiceAPI::DocumentAttachmentCreate]?

      attr_accessor billing_address: String?

      attr_accessor billing_address_recipient: String?

      attr_accessor charges: ::Array[EInvoiceAPI::DocumentCreate::Charge]?

      attr_reader currency: EInvoiceAPI::Models::currency_code?

      def currency=: (
        EInvoiceAPI::Models::currency_code
      ) -> EInvoiceAPI::Models::currency_code

      attr_accessor customer_address: String?

      attr_accessor customer_address_recipient: String?

      attr_accessor customer_email: String?

      attr_accessor customer_id: String?

      attr_accessor customer_name: String?

      attr_accessor customer_tax_id: String?

      attr_reader direction: EInvoiceAPI::Models::document_direction?

      def direction=: (
        EInvoiceAPI::Models::document_direction
      ) -> EInvoiceAPI::Models::document_direction

      attr_reader document_type: EInvoiceAPI::Models::document_type?

      def document_type=: (
        EInvoiceAPI::Models::document_type
      ) -> EInvoiceAPI::Models::document_type

      attr_accessor due_date: Date?

      attr_accessor invoice_date: Date?

      attr_accessor invoice_id: String?

      attr_accessor invoice_total: EInvoiceAPI::Models::DocumentCreate::invoice_total?

      attr_reader items: ::Array[EInvoiceAPI::DocumentCreate::Item]?

      def items=: (
        ::Array[EInvoiceAPI::DocumentCreate::Item]
      ) -> ::Array[EInvoiceAPI::DocumentCreate::Item]

      attr_accessor note: String?

      attr_accessor payment_details: ::Array[EInvoiceAPI::PaymentDetailCreate]?

      attr_accessor payment_term: String?

      attr_accessor previous_unpaid_balance: EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance?

      attr_accessor purchase_order: String?

      attr_accessor remittance_address: String?

      attr_accessor remittance_address_recipient: String?

      attr_accessor service_address: String?

      attr_accessor service_address_recipient: String?

      attr_accessor service_end_date: Date?

      attr_accessor service_start_date: Date?

      attr_accessor shipping_address: String?

      attr_accessor shipping_address_recipient: String?

      attr_reader state: EInvoiceAPI::Models::document_state?

      def state=: (
        EInvoiceAPI::Models::document_state
      ) -> EInvoiceAPI::Models::document_state

      attr_accessor subtotal: EInvoiceAPI::Models::DocumentCreate::subtotal?

      attr_reader tax_code: EInvoiceAPI::Models::DocumentCreate::tax_code?

      def tax_code=: (
        EInvoiceAPI::Models::DocumentCreate::tax_code
      ) -> EInvoiceAPI::Models::DocumentCreate::tax_code

      attr_accessor tax_details: ::Array[EInvoiceAPI::DocumentCreate::TaxDetail]?

      attr_accessor total_discount: EInvoiceAPI::Models::DocumentCreate::total_discount?

      attr_accessor total_tax: EInvoiceAPI::Models::DocumentCreate::total_tax?

      attr_accessor vatex: EInvoiceAPI::Models::DocumentCreate::vatex?

      attr_accessor vatex_note: String?

      attr_accessor vendor_address: String?

      attr_accessor vendor_address_recipient: String?

      attr_accessor vendor_email: String?

      attr_accessor vendor_name: String?

      attr_accessor vendor_tax_id: String?

      def initialize: (
        ?allowances: ::Array[EInvoiceAPI::DocumentCreate::Allowance]?,
        ?amount_due: EInvoiceAPI::Models::DocumentCreate::amount_due?,
        ?attachments: ::Array[EInvoiceAPI::DocumentAttachmentCreate]?,
        ?billing_address: String?,
        ?billing_address_recipient: String?,
        ?charges: ::Array[EInvoiceAPI::DocumentCreate::Charge]?,
        ?currency: EInvoiceAPI::Models::currency_code,
        ?customer_address: String?,
        ?customer_address_recipient: String?,
        ?customer_email: String?,
        ?customer_id: String?,
        ?customer_name: String?,
        ?customer_tax_id: String?,
        ?direction: EInvoiceAPI::Models::document_direction,
        ?document_type: EInvoiceAPI::Models::document_type,
        ?due_date: Date?,
        ?invoice_date: Date?,
        ?invoice_id: String?,
        ?invoice_total: EInvoiceAPI::Models::DocumentCreate::invoice_total?,
        ?items: ::Array[EInvoiceAPI::DocumentCreate::Item],
        ?note: String?,
        ?payment_details: ::Array[EInvoiceAPI::PaymentDetailCreate]?,
        ?payment_term: String?,
        ?previous_unpaid_balance: EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance?,
        ?purchase_order: String?,
        ?remittance_address: String?,
        ?remittance_address_recipient: String?,
        ?service_address: String?,
        ?service_address_recipient: String?,
        ?service_end_date: Date?,
        ?service_start_date: Date?,
        ?shipping_address: String?,
        ?shipping_address_recipient: String?,
        ?state: EInvoiceAPI::Models::document_state,
        ?subtotal: EInvoiceAPI::Models::DocumentCreate::subtotal?,
        ?tax_code: EInvoiceAPI::Models::DocumentCreate::tax_code,
        ?tax_details: ::Array[EInvoiceAPI::DocumentCreate::TaxDetail]?,
        ?total_discount: EInvoiceAPI::Models::DocumentCreate::total_discount?,
        ?total_tax: EInvoiceAPI::Models::DocumentCreate::total_tax?,
        ?vatex: EInvoiceAPI::Models::DocumentCreate::vatex?,
        ?vatex_note: String?,
        ?vendor_address: String?,
        ?vendor_address_recipient: String?,
        ?vendor_email: String?,
        ?vendor_name: String?,
        ?vendor_tax_id: String?
      ) -> void

      def to_hash: -> {
        allowances: ::Array[EInvoiceAPI::DocumentCreate::Allowance]?,
        amount_due: EInvoiceAPI::Models::DocumentCreate::amount_due?,
        attachments: ::Array[EInvoiceAPI::DocumentAttachmentCreate]?,
        billing_address: String?,
        billing_address_recipient: String?,
        charges: ::Array[EInvoiceAPI::DocumentCreate::Charge]?,
        currency: EInvoiceAPI::Models::currency_code,
        customer_address: String?,
        customer_address_recipient: String?,
        customer_email: String?,
        customer_id: String?,
        customer_name: String?,
        customer_tax_id: String?,
        direction: EInvoiceAPI::Models::document_direction,
        document_type: EInvoiceAPI::Models::document_type,
        due_date: Date?,
        invoice_date: Date?,
        invoice_id: String?,
        invoice_total: EInvoiceAPI::Models::DocumentCreate::invoice_total?,
        items: ::Array[EInvoiceAPI::DocumentCreate::Item],
        note: String?,
        payment_details: ::Array[EInvoiceAPI::PaymentDetailCreate]?,
        payment_term: String?,
        previous_unpaid_balance: EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance?,
        purchase_order: String?,
        remittance_address: String?,
        remittance_address_recipient: String?,
        service_address: String?,
        service_address_recipient: String?,
        service_end_date: Date?,
        service_start_date: Date?,
        shipping_address: String?,
        shipping_address_recipient: String?,
        state: EInvoiceAPI::Models::document_state,
        subtotal: EInvoiceAPI::Models::DocumentCreate::subtotal?,
        tax_code: EInvoiceAPI::Models::DocumentCreate::tax_code,
        tax_details: ::Array[EInvoiceAPI::DocumentCreate::TaxDetail]?,
        total_discount: EInvoiceAPI::Models::DocumentCreate::total_discount?,
        total_tax: EInvoiceAPI::Models::DocumentCreate::total_tax?,
        vatex: EInvoiceAPI::Models::DocumentCreate::vatex?,
        vatex_note: String?,
        vendor_address: String?,
        vendor_address_recipient: String?,
        vendor_email: String?,
        vendor_name: String?,
        vendor_tax_id: String?
      }

      type allowance =
        {
          amount: EInvoiceAPI::Models::DocumentCreate::Allowance::amount?,
          base_amount: EInvoiceAPI::Models::DocumentCreate::Allowance::base_amount?,
          multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Allowance::multiplier_factor?,
          reason: String?,
          reason_code: String?,
          tax_code: EInvoiceAPI::Models::DocumentCreate::Allowance::tax_code?,
          tax_rate: String?
        }

      class Allowance < EInvoiceAPI::Internal::Type::BaseModel
        attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::Allowance::amount?

        attr_accessor base_amount: EInvoiceAPI::Models::DocumentCreate::Allowance::base_amount?

        attr_accessor multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Allowance::multiplier_factor?

        attr_accessor reason: String?

        attr_accessor reason_code: String?

        attr_accessor tax_code: EInvoiceAPI::Models::DocumentCreate::Allowance::tax_code?

        attr_accessor tax_rate: String?

        def initialize: (
          ?amount: EInvoiceAPI::Models::DocumentCreate::Allowance::amount?,
          ?base_amount: EInvoiceAPI::Models::DocumentCreate::Allowance::base_amount?,
          ?multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Allowance::multiplier_factor?,
          ?reason: String?,
          ?reason_code: String?,
          ?tax_code: EInvoiceAPI::Models::DocumentCreate::Allowance::tax_code?,
          ?tax_rate: String?
        ) -> void

        def to_hash: -> {
          amount: EInvoiceAPI::Models::DocumentCreate::Allowance::amount?,
          base_amount: EInvoiceAPI::Models::DocumentCreate::Allowance::base_amount?,
          multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Allowance::multiplier_factor?,
          reason: String?,
          reason_code: String?,
          tax_code: EInvoiceAPI::Models::DocumentCreate::Allowance::tax_code?,
          tax_rate: String?
        }

        type amount = Float | String

        module Amount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Allowance::amount]
        end

        type base_amount = Float | String

        module BaseAmount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Allowance::base_amount]
        end

        type multiplier_factor = Float | String

        module MultiplierFactor
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Allowance::multiplier_factor]
        end

        type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

        module TaxCode
          extend EInvoiceAPI::Internal::Type::Enum

          AE: :AE
          E: :E
          S: :S
          Z: :Z
          G: :G
          O: :O
          K: :K
          L: :L
          M: :M
          B: :B

          def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Allowance::tax_code]
        end
      end

      type amount_due = Float | String

      module AmountDue
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::amount_due]
      end

      type charge =
        {
          amount: EInvoiceAPI::Models::DocumentCreate::Charge::amount?,
          base_amount: EInvoiceAPI::Models::DocumentCreate::Charge::base_amount?,
          multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Charge::multiplier_factor?,
          reason: String?,
          reason_code: String?,
          tax_code: EInvoiceAPI::Models::DocumentCreate::Charge::tax_code?,
          tax_rate: String?
        }

      class Charge < EInvoiceAPI::Internal::Type::BaseModel
        attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::Charge::amount?

        attr_accessor base_amount: EInvoiceAPI::Models::DocumentCreate::Charge::base_amount?

        attr_accessor multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Charge::multiplier_factor?

        attr_accessor reason: String?

        attr_accessor reason_code: String?

        attr_accessor tax_code: EInvoiceAPI::Models::DocumentCreate::Charge::tax_code?

        attr_accessor tax_rate: String?

        def initialize: (
          ?amount: EInvoiceAPI::Models::DocumentCreate::Charge::amount?,
          ?base_amount: EInvoiceAPI::Models::DocumentCreate::Charge::base_amount?,
          ?multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Charge::multiplier_factor?,
          ?reason: String?,
          ?reason_code: String?,
          ?tax_code: EInvoiceAPI::Models::DocumentCreate::Charge::tax_code?,
          ?tax_rate: String?
        ) -> void

        def to_hash: -> {
          amount: EInvoiceAPI::Models::DocumentCreate::Charge::amount?,
          base_amount: EInvoiceAPI::Models::DocumentCreate::Charge::base_amount?,
          multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Charge::multiplier_factor?,
          reason: String?,
          reason_code: String?,
          tax_code: EInvoiceAPI::Models::DocumentCreate::Charge::tax_code?,
          tax_rate: String?
        }

        type amount = Float | String

        module Amount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Charge::amount]
        end

        type base_amount = Float | String

        module BaseAmount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Charge::base_amount]
        end

        type multiplier_factor = Float | String

        module MultiplierFactor
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Charge::multiplier_factor]
        end

        type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

        module TaxCode
          extend EInvoiceAPI::Internal::Type::Enum

          AE: :AE
          E: :E
          S: :S
          Z: :Z
          G: :G
          O: :O
          K: :K
          L: :L
          M: :M
          B: :B

          def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Charge::tax_code]
        end
      end

      type invoice_total = Float | String

      module InvoiceTotal
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::invoice_total]
      end

      type item =
        {
          allowances: ::Array[EInvoiceAPI::DocumentCreate::Item::Allowance]?,
          amount: EInvoiceAPI::Models::DocumentCreate::Item::amount?,
          charges: ::Array[EInvoiceAPI::DocumentCreate::Item::Charge]?,
          date: nil,
          description: String?,
          product_code: String?,
          quantity: EInvoiceAPI::Models::DocumentCreate::Item::quantity?,
          tax: EInvoiceAPI::Models::DocumentCreate::Item::tax?,
          tax_rate: String?,
          unit: EInvoiceAPI::Models::unit_of_measure_code?,
          unit_price: EInvoiceAPI::Models::DocumentCreate::Item::unit_price?
        }

      class Item < EInvoiceAPI::Internal::Type::BaseModel
        attr_accessor allowances: ::Array[EInvoiceAPI::DocumentCreate::Item::Allowance]?

        attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::Item::amount?

        attr_accessor charges: ::Array[EInvoiceAPI::DocumentCreate::Item::Charge]?

        attr_accessor date: nil

        attr_accessor description: String?

        attr_accessor product_code: String?

        attr_accessor quantity: EInvoiceAPI::Models::DocumentCreate::Item::quantity?

        attr_accessor tax: EInvoiceAPI::Models::DocumentCreate::Item::tax?

        attr_accessor tax_rate: String?

        attr_accessor unit: EInvoiceAPI::Models::unit_of_measure_code?

        attr_accessor unit_price: EInvoiceAPI::Models::DocumentCreate::Item::unit_price?

        def initialize: (
          ?allowances: ::Array[EInvoiceAPI::DocumentCreate::Item::Allowance]?,
          ?amount: EInvoiceAPI::Models::DocumentCreate::Item::amount?,
          ?charges: ::Array[EInvoiceAPI::DocumentCreate::Item::Charge]?,
          ?date: nil,
          ?description: String?,
          ?product_code: String?,
          ?quantity: EInvoiceAPI::Models::DocumentCreate::Item::quantity?,
          ?tax: EInvoiceAPI::Models::DocumentCreate::Item::tax?,
          ?tax_rate: String?,
          ?unit: EInvoiceAPI::Models::unit_of_measure_code?,
          ?unit_price: EInvoiceAPI::Models::DocumentCreate::Item::unit_price?
        ) -> void

        def to_hash: -> {
          allowances: ::Array[EInvoiceAPI::DocumentCreate::Item::Allowance]?,
          amount: EInvoiceAPI::Models::DocumentCreate::Item::amount?,
          charges: ::Array[EInvoiceAPI::DocumentCreate::Item::Charge]?,
          date: nil,
          description: String?,
          product_code: String?,
          quantity: EInvoiceAPI::Models::DocumentCreate::Item::quantity?,
          tax: EInvoiceAPI::Models::DocumentCreate::Item::tax?,
          tax_rate: String?,
          unit: EInvoiceAPI::Models::unit_of_measure_code?,
          unit_price: EInvoiceAPI::Models::DocumentCreate::Item::unit_price?
        }

        type allowance =
          {
            amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::amount?,
            base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::base_amount?,
            multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::multiplier_factor?,
            reason: String?,
            reason_code: String?,
            tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::tax_code?,
            tax_rate: String?
          }

        class Allowance < EInvoiceAPI::Internal::Type::BaseModel
          attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::amount?

          attr_accessor base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::base_amount?

          attr_accessor multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::multiplier_factor?

          attr_accessor reason: String?

          attr_accessor reason_code: String?

          attr_accessor tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::tax_code?

          attr_accessor tax_rate: String?

          def initialize: (
            ?amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::amount?,
            ?base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::base_amount?,
            ?multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::multiplier_factor?,
            ?reason: String?,
            ?reason_code: String?,
            ?tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::tax_code?,
            ?tax_rate: String?
          ) -> void

          def to_hash: -> {
            amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::amount?,
            base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::base_amount?,
            multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::multiplier_factor?,
            reason: String?,
            reason_code: String?,
            tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Allowance::tax_code?,
            tax_rate: String?
          }

          type amount = Float | String

          module Amount
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Allowance::amount]
          end

          type base_amount = Float | String

          module BaseAmount
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Allowance::base_amount]
          end

          type multiplier_factor = Float | String

          module MultiplierFactor
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Allowance::multiplier_factor]
          end

          type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

          module TaxCode
            extend EInvoiceAPI::Internal::Type::Enum

            AE: :AE
            E: :E
            S: :S
            Z: :Z
            G: :G
            O: :O
            K: :K
            L: :L
            M: :M
            B: :B

            def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Allowance::tax_code]
          end
        end

        type amount = Float | String

        module Amount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::amount]
        end

        type charge =
          {
            amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::amount?,
            base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::base_amount?,
            multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Charge::multiplier_factor?,
            reason: String?,
            reason_code: String?,
            tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Charge::tax_code?,
            tax_rate: String?
          }

        class Charge < EInvoiceAPI::Internal::Type::BaseModel
          attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::amount?

          attr_accessor base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::base_amount?

          attr_accessor multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Charge::multiplier_factor?

          attr_accessor reason: String?

          attr_accessor reason_code: String?

          attr_accessor tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Charge::tax_code?

          attr_accessor tax_rate: String?

          def initialize: (
            ?amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::amount?,
            ?base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::base_amount?,
            ?multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Charge::multiplier_factor?,
            ?reason: String?,
            ?reason_code: String?,
            ?tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Charge::tax_code?,
            ?tax_rate: String?
          ) -> void

          def to_hash: -> {
            amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::amount?,
            base_amount: EInvoiceAPI::Models::DocumentCreate::Item::Charge::base_amount?,
            multiplier_factor: EInvoiceAPI::Models::DocumentCreate::Item::Charge::multiplier_factor?,
            reason: String?,
            reason_code: String?,
            tax_code: EInvoiceAPI::Models::DocumentCreate::Item::Charge::tax_code?,
            tax_rate: String?
          }

          type amount = Float | String

          module Amount
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Charge::amount]
          end

          type base_amount = Float | String

          module BaseAmount
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Charge::base_amount]
          end

          type multiplier_factor = Float | String

          module MultiplierFactor
            extend EInvoiceAPI::Internal::Type::Union

            def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Charge::multiplier_factor]
          end

          type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

          module TaxCode
            extend EInvoiceAPI::Internal::Type::Enum

            AE: :AE
            E: :E
            S: :S
            Z: :Z
            G: :G
            O: :O
            K: :K
            L: :L
            M: :M
            B: :B

            def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::Charge::tax_code]
          end
        end

        type quantity = Float | String

        module Quantity
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::quantity]
        end

        type tax = Float | String

        module Tax
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::tax]
        end

        type unit_price = Float | String

        module UnitPrice
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::Item::unit_price]
        end
      end

      type previous_unpaid_balance = Float | String

      module PreviousUnpaidBalance
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance]
      end

      type subtotal = Float | String

      module Subtotal
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::subtotal]
      end

      type tax_code = :AE | :E | :S | :Z | :G | :O | :K | :L | :M | :B

      module TaxCode
        extend EInvoiceAPI::Internal::Type::Enum

        AE: :AE
        E: :E
        S: :S
        Z: :Z
        G: :G
        O: :O
        K: :K
        L: :L
        M: :M
        B: :B

        def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::tax_code]
      end

      type tax_detail =
        {
          amount: EInvoiceAPI::Models::DocumentCreate::TaxDetail::amount?,
          rate: String?
        }

      class TaxDetail < EInvoiceAPI::Internal::Type::BaseModel
        attr_accessor amount: EInvoiceAPI::Models::DocumentCreate::TaxDetail::amount?

        attr_accessor rate: String?

        def initialize: (
          ?amount: EInvoiceAPI::Models::DocumentCreate::TaxDetail::amount?,
          ?rate: String?
        ) -> void

        def to_hash: -> {
          amount: EInvoiceAPI::Models::DocumentCreate::TaxDetail::amount?,
          rate: String?
        }

        type amount = Float | String

        module Amount
          extend EInvoiceAPI::Internal::Type::Union

          def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::TaxDetail::amount]
        end
      end

      type total_discount = Float | String

      module TotalDiscount
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::total_discount]
      end

      type total_tax = Float | String

      module TotalTax
        extend EInvoiceAPI::Internal::Type::Union

        def self?.variants: -> ::Array[EInvoiceAPI::Models::DocumentCreate::total_tax]
      end

      type vatex =
        :"VATEX-EU-79-C"
        | :"VATEX-EU-132"
        | :"VATEX-EU-132-1A"
        | :"VATEX-EU-132-1B"
        | :"VATEX-EU-132-1C"
        | :"VATEX-EU-132-1D"
        | :"VATEX-EU-132-1E"
        | :"VATEX-EU-132-1F"
        | :"VATEX-EU-132-1G"
        | :"VATEX-EU-132-1H"
        | :"VATEX-EU-132-1I"
        | :"VATEX-EU-132-1J"
        | :"VATEX-EU-132-1K"
        | :"VATEX-EU-132-1L"
        | :"VATEX-EU-132-1M"
        | :"VATEX-EU-132-1N"
        | :"VATEX-EU-132-1O"
        | :"VATEX-EU-132-1P"
        | :"VATEX-EU-132-1Q"
        | :"VATEX-EU-143"
        | :"VATEX-EU-143-1A"
        | :"VATEX-EU-143-1B"
        | :"VATEX-EU-143-1C"
        | :"VATEX-EU-143-1D"
        | :"VATEX-EU-143-1E"
        | :"VATEX-EU-143-1F"
        | :"VATEX-EU-143-1FA"
        | :"VATEX-EU-143-1G"
        | :"VATEX-EU-143-1H"
        | :"VATEX-EU-143-1I"
        | :"VATEX-EU-143-1J"
        | :"VATEX-EU-143-1K"
        | :"VATEX-EU-143-1L"
        | :"VATEX-EU-144"
        | :"VATEX-EU-146-1E"
        | :"VATEX-EU-148"
        | :"VATEX-EU-148-A"
        | :"VATEX-EU-148-B"
        | :"VATEX-EU-148-C"
        | :"VATEX-EU-148-D"
        | :"VATEX-EU-148-E"
        | :"VATEX-EU-148-F"
        | :"VATEX-EU-148-G"
        | :"VATEX-EU-151"
        | :"VATEX-EU-151-1A"
        | :"VATEX-EU-151-1AA"
        | :"VATEX-EU-151-1B"
        | :"VATEX-EU-151-1C"
        | :"VATEX-EU-151-1D"
        | :"VATEX-EU-151-1E"
        | :"VATEX-EU-159"
        | :"VATEX-EU-309"
        | :"VATEX-EU-AE"
        | :"VATEX-EU-D"
        | :"VATEX-EU-F"
        | :"VATEX-EU-G"
        | :"VATEX-EU-I"
        | :"VATEX-EU-IC"
        | :"VATEX-EU-O"
        | :"VATEX-EU-J"
        | :"VATEX-FR-FRANCHISE"
        | :"VATEX-FR-CNWVAT"

      module Vatex
        extend EInvoiceAPI::Internal::Type::Enum

        VATEX_EU_79_C: :"VATEX-EU-79-C"
        VATEX_EU_132: :"VATEX-EU-132"
        VATEX_EU_132_1_A: :"VATEX-EU-132-1A"
        VATEX_EU_132_1_B: :"VATEX-EU-132-1B"
        VATEX_EU_132_1_C: :"VATEX-EU-132-1C"
        VATEX_EU_132_1_D: :"VATEX-EU-132-1D"
        VATEX_EU_132_1_E: :"VATEX-EU-132-1E"
        VATEX_EU_132_1_F: :"VATEX-EU-132-1F"
        VATEX_EU_132_1_G: :"VATEX-EU-132-1G"
        VATEX_EU_132_1_H: :"VATEX-EU-132-1H"
        VATEX_EU_132_1_I: :"VATEX-EU-132-1I"
        VATEX_EU_132_1_J: :"VATEX-EU-132-1J"
        VATEX_EU_132_1_K: :"VATEX-EU-132-1K"
        VATEX_EU_132_1_L: :"VATEX-EU-132-1L"
        VATEX_EU_132_1_M: :"VATEX-EU-132-1M"
        VATEX_EU_132_1_N: :"VATEX-EU-132-1N"
        VATEX_EU_132_1_O: :"VATEX-EU-132-1O"
        VATEX_EU_132_1_P: :"VATEX-EU-132-1P"
        VATEX_EU_132_1_Q: :"VATEX-EU-132-1Q"
        VATEX_EU_143: :"VATEX-EU-143"
        VATEX_EU_143_1_A: :"VATEX-EU-143-1A"
        VATEX_EU_143_1_B: :"VATEX-EU-143-1B"
        VATEX_EU_143_1_C: :"VATEX-EU-143-1C"
        VATEX_EU_143_1_D: :"VATEX-EU-143-1D"
        VATEX_EU_143_1_E: :"VATEX-EU-143-1E"
        VATEX_EU_143_1_F: :"VATEX-EU-143-1F"
        VATEX_EU_143_1_FA: :"VATEX-EU-143-1FA"
        VATEX_EU_143_1_G: :"VATEX-EU-143-1G"
        VATEX_EU_143_1_H: :"VATEX-EU-143-1H"
        VATEX_EU_143_1_I: :"VATEX-EU-143-1I"
        VATEX_EU_143_1_J: :"VATEX-EU-143-1J"
        VATEX_EU_143_1_K: :"VATEX-EU-143-1K"
        VATEX_EU_143_1_L: :"VATEX-EU-143-1L"
        VATEX_EU_144: :"VATEX-EU-144"
        VATEX_EU_146_1_E: :"VATEX-EU-146-1E"
        VATEX_EU_148: :"VATEX-EU-148"
        VATEX_EU_148_A: :"VATEX-EU-148-A"
        VATEX_EU_148_B: :"VATEX-EU-148-B"
        VATEX_EU_148_C: :"VATEX-EU-148-C"
        VATEX_EU_148_D: :"VATEX-EU-148-D"
        VATEX_EU_148_E: :"VATEX-EU-148-E"
        VATEX_EU_148_F: :"VATEX-EU-148-F"
        VATEX_EU_148_G: :"VATEX-EU-148-G"
        VATEX_EU_151: :"VATEX-EU-151"
        VATEX_EU_151_1_A: :"VATEX-EU-151-1A"
        VATEX_EU_151_1_AA: :"VATEX-EU-151-1AA"
        VATEX_EU_151_1_B: :"VATEX-EU-151-1B"
        VATEX_EU_151_1_C: :"VATEX-EU-151-1C"
        VATEX_EU_151_1_D: :"VATEX-EU-151-1D"
        VATEX_EU_151_1_E: :"VATEX-EU-151-1E"
        VATEX_EU_159: :"VATEX-EU-159"
        VATEX_EU_309: :"VATEX-EU-309"
        VATEX_EU_AE: :"VATEX-EU-AE"
        VATEX_EU_D: :"VATEX-EU-D"
        VATEX_EU_F: :"VATEX-EU-F"
        VATEX_EU_G: :"VATEX-EU-G"
        VATEX_EU_I: :"VATEX-EU-I"
        VATEX_EU_IC: :"VATEX-EU-IC"
        VATEX_EU_O: :"VATEX-EU-O"
        VATEX_EU_J: :"VATEX-EU-J"
        VATEX_FR_FRANCHISE: :"VATEX-FR-FRANCHISE"
        VATEX_FR_CNWVAT: :"VATEX-FR-CNWVAT"

        def self?.values: -> ::Array[EInvoiceAPI::Models::DocumentCreate::vatex]
      end
    end
  end
end
