module EInvoiceAPI
  module Models
    type document_create_params =
      {  } & EInvoiceAPI::Internal::Type::request_parameters

    class DocumentCreateParams < EInvoiceAPI::Models::DocumentCreate
      extend EInvoiceAPI::Internal::Type::RequestParameters::Converter
      include EInvoiceAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: EInvoiceAPI::request_opts) -> void

      def to_hash: -> { request_options: EInvoiceAPI::RequestOptions }
    end
  end
end
