module EInvoiceAPI
  module Models
    type lookup_retrieve_params =
      { peppol_id: String } & EInvoiceAPI::Internal::Type::request_parameters

    class LookupRetrieveParams < EInvoiceAPI::Internal::Type::BaseModel
      extend EInvoiceAPI::Internal::Type::RequestParameters::Converter
      include EInvoiceAPI::Internal::Type::RequestParameters

      attr_accessor peppol_id: String

      def initialize: (
        peppol_id: String,
        ?request_options: EInvoiceAPI::request_opts
      ) -> void

      def to_hash: -> {
        peppol_id: String,
        request_options: EInvoiceAPI::RequestOptions
      }
    end
  end
end
