module EInvoiceAPI
  module Models
    type payment_detail_create =
      {
        bank_account_number: String?,
        iban: String?,
        payment_reference: String?,
        swift: String?
      }

    class PaymentDetailCreate < EInvoiceAPI::Internal::Type::BaseModel
      attr_accessor bank_account_number: String?

      attr_accessor iban: String?

      attr_accessor payment_reference: String?

      attr_accessor swift: String?

      def initialize: (
        ?bank_account_number: String?,
        ?iban: String?,
        ?payment_reference: String?,
        ?swift: String?
      ) -> void

      def to_hash: -> {
        bank_account_number: String?,
        iban: String?,
        payment_reference: String?,
        swift: String?
      }
    end
  end
end
