module EInvoice
  module Internal
    class DocumentsNumberPage[Elem]
      include EInvoice::Internal::Type::BasePage[Elem]

      attr_accessor items: ::Array[Elem]?

      attr_accessor page: Integer

      attr_accessor page_size: Integer

      attr_accessor total: Integer

      def inspect: -> String
    end
  end
end
