module EInvoice
  module Models
    module Documents
      type attachment_list_response =
        ::Array[EInvoice::Documents::DocumentAttachment]

      AttachmentListResponse: EInvoice::Internal::Type::Converter
    end
  end
end
