module EInvoice
  module Models
    module Documents
      type ubl_get_params = {  } & EInvoice::Internal::Type::request_parameters

      class UblGetParams < EInvoice::Internal::Type::BaseModel
        extend EInvoice::Internal::Type::RequestParameters::Converter
        include EInvoice::Internal::Type::RequestParameters

        def initialize: (?request_options: EInvoice::request_opts) -> void

        def to_hash: -> { request_options: EInvoice::RequestOptions }
      end
    end
  end
end
