module EInvoiceAPI
  module Resources
    class Documents
      class Attachments
        def retrieve: (
          String attachment_id,
          document_id: String,
          ?request_options: EInvoiceAPI::request_opts
        ) -> EInvoiceAPI::Documents::DocumentAttachment

        def list: (
          String document_id,
          ?request_options: EInvoiceAPI::request_opts
        ) -> EInvoiceAPI::Models::Documents::attachment_list_response

        def delete: (
          String attachment_id,
          document_id: String,
          ?request_options: EInvoiceAPI::request_opts
        ) -> EInvoiceAPI::Models::Documents::AttachmentDeleteResponse

        def add: (
          String document_id,
          file: EInvoiceAPI::Internal::file_input,
          ?request_options: EInvoiceAPI::request_opts
        ) -> EInvoiceAPI::Documents::DocumentAttachment

        def initialize: (client: EInvoiceAPI::Client) -> void
      end
    end
  end
end
