module EInvoiceAPI
  module Resources
    class Documents
      class Ubl
        def get: (
          String document_id,
          ?request_options: EInvoiceAPI::request_opts
        ) -> EInvoiceAPI::Models::Documents::UblGetResponse

        def initialize: (client: EInvoiceAPI::Client) -> void
      end
    end
  end
end
