# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "e_invoice/version"
require_relative "e_invoice/internal/util"
require_relative "e_invoice/internal/type/converter"
require_relative "e_invoice/internal/type/unknown"
require_relative "e_invoice/internal/type/boolean"
require_relative "e_invoice/internal/type/file_input"
require_relative "e_invoice/internal/type/enum"
require_relative "e_invoice/internal/type/union"
require_relative "e_invoice/internal/type/array_of"
require_relative "e_invoice/internal/type/hash_of"
require_relative "e_invoice/internal/type/base_model"
require_relative "e_invoice/internal/type/base_page"
require_relative "e_invoice/internal/type/request_parameters"
require_relative "e_invoice/internal"
require_relative "e_invoice/request_options"
require_relative "e_invoice/file_part"
require_relative "e_invoice/errors"
require_relative "e_invoice/internal/transport/base_client"
require_relative "e_invoice/internal/transport/pooled_net_requester"
require_relative "e_invoice/client"
require_relative "e_invoice/internal/documents_number_page"
require_relative "e_invoice/models/document_create"
require_relative "e_invoice/models/certificate"
require_relative "e_invoice/models/currency_code"
require_relative "e_invoice/models/document_attachment_create"
require_relative "e_invoice/models/document_create_params"
require_relative "e_invoice/models/document_delete_params"
require_relative "e_invoice/models/document_delete_response"
require_relative "e_invoice/models/document_direction"
require_relative "e_invoice/models/document_response"
require_relative "e_invoice/models/document_retrieve_params"
require_relative "e_invoice/models/documents/attachment_add_params"
require_relative "e_invoice/models/documents/attachment_delete_params"
require_relative "e_invoice/models/documents/attachment_delete_response"
require_relative "e_invoice/models/documents/attachment_list_params"
require_relative "e_invoice/models/documents/attachment_list_response"
require_relative "e_invoice/models/documents/attachment_retrieve_params"
require_relative "e_invoice/models/documents/document_attachment"
require_relative "e_invoice/models/documents/ubl_get_params"
require_relative "e_invoice/models/documents/ubl_get_response"
require_relative "e_invoice/models/document_send_params"
require_relative "e_invoice/models/document_state"
require_relative "e_invoice/models/document_type"
require_relative "e_invoice/models/inbox_list_credit_notes_params"
require_relative "e_invoice/models/inbox_list_invoices_params"
require_relative "e_invoice/models/inbox_list_params"
require_relative "e_invoice/models/lookup_retrieve_params"
require_relative "e_invoice/models/lookup_retrieve_response"
require_relative "e_invoice/models/outbox_list_draft_documents_params"
require_relative "e_invoice/models/outbox_list_received_documents_params"
require_relative "e_invoice/models/paginated_document_response"
require_relative "e_invoice/models/payment_detail_create"
require_relative "e_invoice/models/ubl_document_validation"
require_relative "e_invoice/models/unit_of_measure_code"
require_relative "e_invoice/models/validate_validate_json_params"
require_relative "e_invoice/models/validate_validate_peppol_id_params"
require_relative "e_invoice/models/validate_validate_peppol_id_response"
require_relative "e_invoice/models/validate_validate_ubl_params"
require_relative "e_invoice/models/webhook_create_params"
require_relative "e_invoice/models/webhook_delete_params"
require_relative "e_invoice/models/webhook_delete_response"
require_relative "e_invoice/models/webhook_list_params"
require_relative "e_invoice/models/webhook_list_response"
require_relative "e_invoice/models/webhook_response"
require_relative "e_invoice/models/webhook_retrieve_params"
require_relative "e_invoice/models/webhook_update_params"
require_relative "e_invoice/models"
require_relative "e_invoice/resources/documents"
require_relative "e_invoice/resources/documents/attachments"
require_relative "e_invoice/resources/documents/ubl"
require_relative "e_invoice/resources/inbox"
require_relative "e_invoice/resources/lookup"
require_relative "e_invoice/resources/outbox"
require_relative "e_invoice/resources/validate"
require_relative "e_invoice/resources/webhooks"
