module EInvoice
  module Models
    type certificate =
      { status: String, details: ::Hash[Symbol, top]?, error: String? }

    class Certificate < EInvoice::Internal::Type::BaseModel
      attr_accessor status: String

      attr_accessor details: ::Hash[Symbol, top]?

      attr_accessor error: String?

      def initialize: (
        status: String,
        ?details: ::Hash[Symbol, top]?,
        ?error: String?
      ) -> void

      def to_hash: -> {
        status: String,
        details: ::Hash[Symbol, top]?,
        error: String?
      }
    end
  end
end
