module EInvoice
  module Models
    type currency_code =
      :EUR
      | :USD
      | :GBP
      | :JPY
      | :CHF
      | :CAD
      | :AUD
      | :NZD
      | :CNY
      | :INR
      | :SEK
      | :NOK
      | :DKK
      | :SGD
      | :HKD

    module CurrencyCode
      extend EInvoice::Internal::Type::Enum

      EUR: :EUR
      USD: :USD
      GBP: :GBP
      JPY: :JPY
      CHF: :CHF
      CAD: :CAD
      AUD: :AUD
      NZD: :NZD
      CNY: :CNY
      INR: :INR
      SEK: :SEK
      NOK: :NOK
      DKK: :DKK
      SGD: :SGD
      HKD: :HKD

      def self?.values: -> ::Array[EInvoice::Models::currency_code]
    end
  end
end
