module EInvoice
  module Models
    type document_type = :INVOICE | :CREDIT_NOTE

    module DocumentType
      extend EInvoice::Internal::Type::Enum

      INVOICE: :INVOICE
      CREDIT_NOTE: :CREDIT_NOTE

      def self?.values: -> ::Array[EInvoice::Models::document_type]
    end
  end
end
