module EInvoice
  module Models
    type document_create_params =
      {  } & EInvoice::Internal::Type::request_parameters

    class DocumentCreateParams < EInvoice::Models::DocumentCreate
      extend EInvoice::Internal::Type::RequestParameters::Converter
      include EInvoice::Internal::Type::RequestParameters

      def initialize: (?request_options: EInvoice::request_opts) -> void

      def to_hash: -> { request_options: EInvoice::RequestOptions }
    end
  end
end
