module EInvoice
  module Models
    type document_attachment_create =
      {
        file_name: String,
        file_data: String?,
        file_size: Integer,
        file_type: String
      }

    class DocumentAttachmentCreate < EInvoice::Internal::Type::BaseModel
      attr_accessor file_name: String

      attr_accessor file_data: String?

      attr_reader file_size: Integer?

      def file_size=: (Integer) -> Integer

      attr_reader file_type: String?

      def file_type=: (String) -> String

      def initialize: (
        file_name: String,
        ?file_data: String?,
        ?file_size: Integer,
        ?file_type: String
      ) -> void

      def to_hash: -> {
        file_name: String,
        file_data: String?,
        file_size: Integer,
        file_type: String
      }
    end
  end
end
