module EInvoice
  module Models
    type webhook_update_params =
      { enabled: bool?, events: ::Array[String]?, url: String? }
      & EInvoice::Internal::Type::request_parameters

    class WebhookUpdateParams < EInvoice::Internal::Type::BaseModel
      extend EInvoice::Internal::Type::RequestParameters::Converter
      include EInvoice::Internal::Type::RequestParameters

      attr_accessor enabled: bool?

      attr_accessor events: ::Array[String]?

      attr_accessor url: String?

      def initialize: (
        ?enabled: bool?,
        ?events: ::Array[String]?,
        ?url: String?,
        ?request_options: EInvoice::request_opts
      ) -> void

      def to_hash: -> {
        enabled: bool?,
        events: ::Array[String]?,
        url: String?,
        request_options: EInvoice::RequestOptions
      }
    end
  end
end
