module EInvoice
  module Models
    type webhook_create_params =
      { events: ::Array[String], url: String, enabled: bool }
      & EInvoice::Internal::Type::request_parameters

    class WebhookCreateParams < EInvoice::Internal::Type::BaseModel
      extend EInvoice::Internal::Type::RequestParameters::Converter
      include EInvoice::Internal::Type::RequestParameters

      attr_accessor events: ::Array[String]

      attr_accessor url: String

      attr_reader enabled: bool?

      def enabled=: (bool) -> bool

      def initialize: (
        events: ::Array[String],
        url: String,
        ?enabled: bool,
        ?request_options: EInvoice::request_opts
      ) -> void

      def to_hash: -> {
        events: ::Array[String],
        url: String,
        enabled: bool,
        request_options: EInvoice::RequestOptions
      }
    end
  end
end
