module EInvoiceAPI
  module Models
    module Documents
      type attachment_retrieve_params =
        { document_id: String }
        & EInvoiceAPI::Internal::Type::request_parameters

      class AttachmentRetrieveParams < EInvoiceAPI::Internal::Type::BaseModel
        extend EInvoiceAPI::Internal::Type::RequestParameters::Converter
        include EInvoiceAPI::Internal::Type::RequestParameters

        attr_accessor document_id: String

        def initialize: (
          document_id: String,
          ?request_options: EInvoiceAPI::request_opts
        ) -> void

        def to_hash: -> {
          document_id: String,
          request_options: EInvoiceAPI::RequestOptions
        }
      end
    end
  end
end
