module EInvoiceAPI
  module Models
    module Documents
      type attachment_list_response =
        ::Array[EInvoiceAPI::Documents::DocumentAttachment]

      AttachmentListResponse: EInvoiceAPI::Internal::Type::Converter
    end
  end
end
