module EInvoiceAPI
  module Resources
    class Documents
      attr_reader attachments: EInvoiceAPI::Resources::Documents::Attachments

      attr_reader ubl: EInvoiceAPI::Resources::Documents::Ubl

      def create: (
        ?amount_due: EInvoiceAPI::Models::DocumentCreate::amount_due?,
        ?attachments: ::Array[EInvoiceAPI::DocumentAttachmentCreate]?,
        ?billing_address: String?,
        ?billing_address_recipient: String?,
        ?currency: EInvoiceAPI::Models::currency_code,
        ?customer_address: String?,
        ?customer_address_recipient: String?,
        ?customer_email: String?,
        ?customer_id: String?,
        ?customer_name: String?,
        ?customer_tax_id: String?,
        ?direction: EInvoiceAPI::Models::document_direction,
        ?document_type: EInvoiceAPI::Models::document_type,
        ?due_date: Date?,
        ?invoice_date: Date?,
        ?invoice_id: String?,
        ?invoice_total: EInvoiceAPI::Models::DocumentCreate::invoice_total?,
        ?items: ::Array[EInvoiceAPI::DocumentCreate::Item]?,
        ?note: String?,
        ?payment_details: ::Array[EInvoiceAPI::PaymentDetailCreate]?,
        ?payment_term: String?,
        ?previous_unpaid_balance: EInvoiceAPI::Models::DocumentCreate::previous_unpaid_balance?,
        ?purchase_order: String?,
        ?remittance_address: String?,
        ?remittance_address_recipient: String?,
        ?service_address: String?,
        ?service_address_recipient: String?,
        ?service_end_date: Date?,
        ?service_start_date: Date?,
        ?shipping_address: String?,
        ?shipping_address_recipient: String?,
        ?state: EInvoiceAPI::Models::document_state,
        ?subtotal: EInvoiceAPI::Models::DocumentCreate::subtotal?,
        ?tax_code: EInvoiceAPI::Models::DocumentCreate::tax_code,
        ?tax_details: ::Array[EInvoiceAPI::DocumentCreate::TaxDetail]?,
        ?total_discount: EInvoiceAPI::Models::DocumentCreate::total_discount?,
        ?total_tax: EInvoiceAPI::Models::DocumentCreate::total_tax?,
        ?vatex: EInvoiceAPI::Models::DocumentCreate::vatex?,
        ?vatex_note: String?,
        ?vendor_address: String?,
        ?vendor_address_recipient: String?,
        ?vendor_email: String?,
        ?vendor_name: String?,
        ?vendor_tax_id: String?,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::DocumentResponse

      def retrieve: (
        String document_id,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::DocumentResponse

      def delete: (
        String document_id,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Models::DocumentDeleteResponse

      def send_: (
        String document_id,
        ?email: String?,
        ?receiver_peppol_id: String?,
        ?receiver_peppol_scheme: String?,
        ?sender_peppol_id: String?,
        ?sender_peppol_scheme: String?,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::DocumentResponse

      def initialize: (client: EInvoiceAPI::Client) -> void
    end
  end
end
