module EInvoiceAPI
  module Resources
    class Inbox
      def list: (
        ?date_from: Time?,
        ?date_to: Time?,
        ?page: Integer,
        ?page_size: Integer,
        ?search: String?,
        ?sender: String?,
        ?state: EInvoiceAPI::Models::document_state?,
        ?type: EInvoiceAPI::Models::document_type?,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Internal::DocumentsNumberPage[EInvoiceAPI::DocumentResponse]

      def list_credit_notes: (
        ?page: Integer,
        ?page_size: Integer,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Internal::DocumentsNumberPage[EInvoiceAPI::DocumentResponse]

      def list_invoices: (
        ?page: Integer,
        ?page_size: Integer,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Internal::DocumentsNumberPage[EInvoiceAPI::DocumentResponse]

      def initialize: (client: EInvoiceAPI::Client) -> void
    end
  end
end
