module EInvoiceAPI
  module Resources
    class Lookup
      def retrieve: (
        peppol_id: String,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Models::LookupRetrieveResponse

      def retrieve_participants: (
        query: String,
        ?country_code: String?,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Models::LookupRetrieveParticipantsResponse

      def initialize: (client: EInvoiceAPI::Client) -> void
    end
  end
end
