module EInvoiceAPI
  module Resources
    class Outbox
      def list_draft_documents: (
        ?page: Integer,
        ?page_size: Integer,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Internal::DocumentsNumberPage[EInvoiceAPI::DocumentResponse]

      def list_received_documents: (
        ?date_from: Time?,
        ?date_to: Time?,
        ?page: Integer,
        ?page_size: Integer,
        ?search: String?,
        ?sender: String?,
        ?state: EInvoiceAPI::Models::document_state?,
        ?type: EInvoiceAPI::Models::document_type?,
        ?request_options: EInvoiceAPI::request_opts
      ) -> EInvoiceAPI::Internal::DocumentsNumberPage[EInvoiceAPI::DocumentResponse]

      def initialize: (client: EInvoiceAPI::Client) -> void
    end
  end
end
