module EInvoice
  module Resources
    class Documents
      class Ubl
        def get: (
          String document_id,
          ?request_options: EInvoice::request_opts
        ) -> EInvoice::Models::Documents::UblGetResponse

        def initialize: (client: EInvoice::Client) -> void
      end
    end
  end
end
