module EInvoice
  module Resources
    class Outbox
      def list_draft_documents: (
        ?page: Integer,
        ?page_size: Integer,
        ?request_options: EInvoice::request_opts
      ) -> EInvoice::Internal::DocumentsNumberPage[EInvoice::DocumentResponse]

      def list_received_documents: (
        ?date_from: Time?,
        ?date_to: Time?,
        ?page: Integer,
        ?page_size: Integer,
        ?search: String?,
        ?sender: String?,
        ?state: EInvoice::Models::document_state?,
        ?type: EInvoice::Models::document_type?,
        ?request_options: EInvoice::request_opts
      ) -> EInvoice::Internal::DocumentsNumberPage[EInvoice::DocumentResponse]

      def initialize: (client: EInvoice::Client) -> void
    end
  end
end
