module EInvoice
  module Resources
    class Validate
      def validate_json: (
        ?amount_due: EInvoice::Models::DocumentCreate::amount_due?,
        ?attachments: ::Array[EInvoice::DocumentAttachmentCreate]?,
        ?billing_address: String?,
        ?billing_address_recipient: String?,
        ?currency: EInvoice::Models::currency_code,
        ?customer_address: String?,
        ?customer_address_recipient: String?,
        ?customer_email: String?,
        ?customer_id: String?,
        ?customer_name: String?,
        ?customer_tax_id: String?,
        ?direction: EInvoice::Models::document_direction,
        ?document_type: EInvoice::Models::document_type,
        ?due_date: Date?,
        ?invoice_date: Date?,
        ?invoice_id: String?,
        ?invoice_total: EInvoice::Models::DocumentCreate::invoice_total?,
        ?items: ::Array[EInvoice::DocumentCreate::Item]?,
        ?note: String?,
        ?payment_details: ::Array[EInvoice::PaymentDetailCreate]?,
        ?payment_term: String?,
        ?previous_unpaid_balance: EInvoice::Models::DocumentCreate::previous_unpaid_balance?,
        ?purchase_order: String?,
        ?remittance_address: String?,
        ?remittance_address_recipient: String?,
        ?service_address: String?,
        ?service_address_recipient: String?,
        ?service_end_date: Date?,
        ?service_start_date: Date?,
        ?shipping_address: String?,
        ?shipping_address_recipient: String?,
        ?state: EInvoice::Models::document_state,
        ?subtotal: EInvoice::Models::DocumentCreate::subtotal?,
        ?tax_details: ::Array[EInvoice::DocumentCreate::TaxDetail]?,
        ?total_discount: EInvoice::Models::DocumentCreate::total_discount?,
        ?total_tax: EInvoice::Models::DocumentCreate::total_tax?,
        ?vendor_address: String?,
        ?vendor_address_recipient: String?,
        ?vendor_email: String?,
        ?vendor_name: String?,
        ?vendor_tax_id: String?,
        ?request_options: EInvoice::request_opts
      ) -> EInvoice::UblDocumentValidation

      def validate_peppol_id: (
        peppol_id: String,
        ?request_options: EInvoice::request_opts
      ) -> EInvoice::Models::ValidateValidatePeppolIDResponse

      def validate_ubl: (
        file: EInvoice::Internal::file_input,
        ?request_options: EInvoice::request_opts
      ) -> EInvoice::UblDocumentValidation

      def initialize: (client: EInvoice::Client) -> void
    end
  end
end
